### ISSUE TITLE
RPS gives an output on who the winner is without taking an input from the user/player

### ISSUE THREAD

**Issue by bun137** [bun137/rock-paper-scissors#1]
## About

This is a bug. When you first run `rps.py`, do not give an input and hit the `SHOOTTTTT!` button, you'll see an output on who the winner is.  This doesn't make sense to have a winner declared without the user giving an input.

## bounty 30

**Comment by maverickayush7** [comment]
can i get this assigned ?

**Comment by ghost** [comment]
I'd like to be assigned to this.

**Comment by SuchitraShankar07** [comment]
could you please assign this to me

**Comment by bun137** [comment]
@maverickayush7 you have been assigned, you can start working on this!

**Comment by pushkar-gr** [comment]
Can I work on this ?

**Comment by bun137** [comment]
@pushkar-gr you can start working on this, do open a draft pr to show your progress in 30 mins
I will assign you in few

**Comment by pushkar-gr** [comment]
@bun137 got my pr ?

**Comment by 7Akshu77** [comment]
can I get this issue

**Comment by bun137** [comment]
@7Akshu77 you can start working on this! assigning you now!

**Comment by bun137** [comment]
@7Akshu77 please open a draft PR in 15 mins to show your progress on the issue!

**Comment by bun137** [comment]
this issue is open to assignments!

**Comment by pushkar-gr** [comment]
Hey @bun137 can I know where I went wrong in my previous PR...
ill retry it

**Comment by sxijyoti** [comment]
can i be assigned this?

**Comment by bun137** [comment]
@sjp-codes you have been assigned, you can start working on this issue! do make a draft PR in 30 mins to show your progress!

**Comment by sid-nc** [comment]
can i get assigned to this

**Comment by ghost** [comment]
@bun137 I'd like to get assigned to this. I've already referenced this issue in my commit

**Comment by bun137** [comment]
@amoghbk  sorry but you cant work on a issue without getting assigned

**Comment by bun137** [comment]
@sid-nc, you have been assigned, do open a draft PR in 30 mins to show your progress!

**Comment by SNEH-17PATEL** [comment]
can i get this issue assigned??????????

**Comment by bun137** [comment]
@SNEH-17PATEL you can start working on this issue, do open a draft PR in 30 mins to show your progress

**Comment by srijan-nodes** [comment]
@bun137 If this gets free again....can I get this?

**Comment by PandaTGOS** [comment]
Can I get assigned to this ?

**Comment by bun137** [comment]
@srijan-nodes you can start working on this issue, do make a draft PR in 30 mins to show your progress!

**Comment by bun137** [comment]
@PandaTGOS you have been assigned!

**Comment by ghost** [comment]
@bun137 Can I be assigned next?
