### ISSUE TITLE
Keep a log of the last three scores

### ISSUE THREAD

**Issue by bun137** [bun137/rock-paper-scissors#2]
## About

When you run `rps.py`, you'll see some statically defined log of the last three game's scores, you need to keep a log of the last three game scores and display the winner of the best of three scores .

**Comment by NJWasTaken** [comment]
Can I be assigned?

**Comment by bun137** [comment]
@NJWasTaken You can start working on this issue! Do open a draft PR in 30 mins to show your progress on the issue!

**Comment by SuchitraShankar07** [comment]
could i be assigned to this?

**Comment by bun137** [comment]
@SuchitraShankar07 you have been assigned, you can start working on this issue! Do open  a draft PR in the next 30 mins to show your progress!

**Comment by KaashviR** [comment]
Can I be assigned this issue?

**Comment by pushkar-gr** [comment]
Can I be assigned ?

**Comment by bun137** [comment]
@SuchitraShankar07 can you please open a draft PR with your progress? its been over 30 mins

**Comment by kexwin** [comment]
can i be assigned to this? :)

**Comment by itsA-D** [comment]
can i be assigned to this

**Comment by NJWasTaken** [comment]
Can i be assigned? I think I've got it functional.
