### ISSUE TITLE
Changes to the UI overall

### ISSUE THREAD

**Issue by bun137** [bun137/rock-paper-scissors#3]
## About

The current UI doesn't highlight the winner of the game is and the images  have a white background, the whole game doesn't have a background and is in boring black, white and grey colours.

Notice when the game is played, there is an audio played every time either the computer or the user wins or loses, this audio is taken from street fighter game so any change in the UI should be around street fighter. 
Note: There is no audio if the game is a tie.

Fix these issue by highlighting the winner of the game, changing the images to a png without the white background and make UI changes to resemble street fighter game.

## Bounty 60

**Comment by tejas-techstack** [comment]
can i get assigned

**Comment by bun137** [comment]
@tejas-techstack assigned!

**Comment by sxijyoti** [comment]
can i be assigned this issue?

**Comment by bun137** [comment]
@tejas-techstack can you please open a pr to show your progress? I would be re-assigning if no progress is seen

**Comment by 411sst** [comment]
can i get assigned?

**Comment by bun137** [comment]
@ssether04 really sorry, but this issue has been assigned and the contributor is showing progress

**Comment by KaashviR** [comment]
Can I be assigned this issue?

**Comment by bun137** [comment]
@KaashviR sorry the contributor has been showing progress
